build:
	npm run build

e2e:
	npm run cypress run --headless

dev:
	npm run dev

check:
	npm run lint
	npm tsc

check-pre-push: check

install:
	npm install

start:
	npm run start

test:
	npm run test
