build:
	npm run build

e2e:
	npm run cypress run --headless

dev:
	npm run dev

check:
	npm run lint
	#npm tsc

check-pre-push: check

fix:
	npm run lint -- --fix

install:
	npm install

lint:
	npm run lint --fix

start:
	npm run start

test:
	npm run test
