apps:
  - name: backend
    script: cd backend && ENV=test cargo run
    env:
      NODE_ENV: test
      ENV: test
  - name: frontend
    script: cd frontend && npm run dev
    env:
      NODE_ENV: test
      ENV: test
