[package]
name = "samasya"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "backend"
path = "src/bin/backend.rs"

[dependencies]
axum = "0.6.18"
tokio = { version = "1.28.0", features = ["full"] }
